using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace JsxCore.Analyzers;

/// <param name="Name">The name the global is imported by from <c>dotnet:globals</c>.</param>
/// <param name="TypeName">
/// The assembly-qualified-ish full name of what it is, or empty when the registration says nothing
/// about that, which is what a factory overload does.
/// </param>
public readonly record struct RegisteredGlobal(string Name, string TypeName);

/// <summary>
/// Writes what the application registers with <c>options.Globals</c> onto its own assembly, so the
/// build can generate real declarations for <c>dotnet:globals</c>.
/// </summary>
/// <remarks>
/// <para>
/// The registrations are ordinary method calls in <c>Program.cs</c>: they exist in source, but they
/// only take effect when the application runs, and a build machine never runs it. Until this, the
/// build wrote an untyped stand-in and every global was <c>any</c>, which is not merely imprecise:
/// under <c>noImplicitAny</c> a callback over an <c>any</c> result is an error, so a project using
/// globals could not build with type checking set to error until someone had run it once. It worked
/// on the machine that had, and failed on the agent that had not.
/// </para>
/// <para>
/// An assembly attribute is the same channel the build already uses for the framework and the
/// optimisation settings, and it travels the same way: the tool that generates declarations loads
/// the assembly it just built, and reads them off it.
/// </para>
/// </remarks>
public static class GlobalRegistrationAnnotations
{
    /// <summary>Metadata key holding the registrations, as <c>name=type</c> pairs.</summary>
    public const string RegistrationsKey = "JsxCoreGlobals";

    /// <summary>
    /// Metadata key saying whether the list above is all of them.
    /// </summary>
    /// <remarks>
    /// False when a registration was found that could not be read, such as one whose name is
    /// computed rather than written. A partial list is worse than none: a missing name would turn a
    /// working import into "has no exported member", so the build keeps the untyped stand-in
    /// instead and behaves as it always did.
    /// </remarks>
    public const string CompleteKey = "JsxCoreGlobalsComplete";

    public static string Emit(IReadOnlyList<RegisteredGlobal> globals, bool complete)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("// Written by JsxCore from the options.Globals.Register calls in this project.");
        builder.AppendLine();

        // Ordered so that reordering the calls does not change the assembly, which would otherwise
        // move the build id and invalidate every cached asset URL for no reason.
        var ordered = globals
            .GroupBy(global => global.Name)
            .Select(group => group.Last())
            .OrderBy(global => global.Name, System.StringComparer.Ordinal)
            .ToList();

        var pairs = string.Join(";", ordered.Select(global => $"{global.Name}={global.TypeName}"));

        builder.Append("[assembly: System.Reflection.AssemblyMetadata(\"")
            .Append(RegistrationsKey).Append("\", \"").Append(Escape(pairs)).AppendLine("\")]");

        builder.Append("[assembly: System.Reflection.AssemblyMetadata(\"")
            .Append(CompleteKey).Append("\", \"").Append(complete ? "true" : "false").AppendLine("\")]");

        return builder.ToString();
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    /// <summary>Reads back what <see cref="Emit"/> wrote.</summary>
    public static IReadOnlyList<RegisteredGlobal> Parse(string? pairs)
    {
        if (string.IsNullOrWhiteSpace(pairs))
        {
            return [];
        }

        var globals = new List<RegisteredGlobal>();

        foreach (var entry in pairs!.Split(';'))
        {
            if (entry.Length == 0)
            {
                continue;
            }

            var separator = entry.IndexOf('=');
            if (separator <= 0)
            {
                continue;
            }

            globals.Add(new RegisteredGlobal(
                entry.Substring(0, separator), entry.Substring(separator + 1)));
        }

        return globals;
    }
}
