using System;
using System.Collections.Generic;
using System.Text;

namespace JsxCore.Analyzers;

public sealed record ViewLocationSettings(
    bool Enabled,
    string ViewsDirectory,
    IReadOnlyList<string> Extensions,
    IReadOnlyList<string> ViewFormats,
    IReadOnlyList<string> AreaFormats,
    bool DefineAttributes);

public static class ViewLocationAnnotations
{
    public const string Namespace = "JetBrains.Annotations";

    // Repeats the defaults on JsxCoreOptions, which an analyzer cannot reference because it
    // loads into the compiler. A test asserts the two agree.
    public static readonly string[] DefaultViewLocationFormats =
    [
        "{ViewsDirectory}/{1}/{0}",
        "{ViewsDirectory}/Shared/{0}",
        "{ViewsDirectory}/{0}"
    ];

    public static readonly string[] DefaultAreaViewLocationFormats =
    [
        "Areas/{2}/{ViewsDirectory}/{1}/{0}",
        "Areas/{2}/{ViewsDirectory}/Shared/{0}",
        "{ViewsDirectory}/Shared/{0}"
    ];

    public static readonly string[] DefaultExtensions = [".tsx", ".jsx"];

    public static string Emit(ViewLocationSettings settings)
    {
        if (settings is null) throw new ArgumentNullException(nameof(settings));

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("// Where JsxCore looks for views. Read by IDEs to resolve View() calls that return");
        builder.AppendLine("// .tsx files rather than Razor pages. No effect at run time.");
        builder.AppendLine();

        // Assembly attributes have to precede any other declaration, so the definitions come last
        // even though they are what the attributes above refer to.
        foreach (var extension in settings.Extensions)
        {
            foreach (var format in settings.ViewFormats)
            {
                Append(builder, "AspMvcViewLocationFormat", format, settings.ViewsDirectory, extension);
            }

            foreach (var format in settings.AreaFormats)
            {
                Append(builder, "AspMvcAreaViewLocationFormat", format, settings.ViewsDirectory, extension);
            }
        }

        // Assembly attributes have to precede any other declaration, so the definitions come last
        // even though they are what the attributes above refer to.
        if (settings.DefineAttributes)
        {
            builder.AppendLine();
            builder.AppendLine(AttributeDefinitions());
        }

        return builder.ToString();
    }

    private static void Append(StringBuilder builder, string attribute, string format, string views, string extension)
    {
        // The placeholders already agree: {0} is the view, {1} the controller, {2} the area.
        var location = "~/" + format.Replace("{ViewsDirectory}", views.Replace('\\', '/').Trim('/')) + extension;

        builder.Append("[assembly: ").Append(Namespace).Append('.').Append(attribute)
            .Append("(\"").Append(location).AppendLine("\")]");
    }

    private static string AttributeDefinitions() => $@"namespace {Namespace}
{{
    [System.Diagnostics.Conditional(""JSXCORE_ANNOTATIONS_NEVER_DEFINED"")]
    [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple = true)]
    internal sealed class AspMvcViewLocationFormatAttribute : System.Attribute
    {{
        public AspMvcViewLocationFormatAttribute(string format) => Format = format;
        public string Format {{ get; }}
    }}

    [System.Diagnostics.Conditional(""JSXCORE_ANNOTATIONS_NEVER_DEFINED"")]
    [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple = true)]
    internal sealed class AspMvcAreaViewLocationFormatAttribute : System.Attribute
    {{
        public AspMvcAreaViewLocationFormatAttribute(string format) => Format = format;
        public string Format {{ get; }}
    }}
}}
";
}
