using System.Text.RegularExpressions;
using JsxCore.Rendering;
using Shouldly;

namespace JsxCore.Tests.Unit.Rendering;

/// <summary>
/// The Content-Security-Policy nonce on the scripts JsxCore writes.
/// </summary>
/// <remarks>
/// Every inline script has to carry it. Missing one is not a partial failure: the policy blocks
/// that script, and a page whose import map or model never runs does not render at all.
/// </remarks>
public class NonceTests
{
    private static DocumentContext Context(string? nonce) => new()
    {
        ViewName = "Home/Index",
        RenderMode = RenderMode.ServerAndClient,
        ServerHtml = "<p>hi</p>",
        ModelJson = "{}",
        ContextJson = "{}",
        ModuleUrl = "/_jsx/v1/views/Home/Index.js",
        ClientSpecifier = "@jsxcore/preact/client",
        ImportMap = new Dictionary<string, string> { ["preact"] = "/_jsx/v1/preact/preact.js" },
        Document = new DocumentOptions(),
        Options = new JsxCoreOptions(),
        HotReloadEnabled = true,
        HotReloadClientUrl = "/_jsx/v1/runtime/hmr-client.js",
        HotReloadEndpoint = "/_jsx/hmr",
        Nonce = nonce
    };

    private static IReadOnlyList<string> ScriptTags(string html) =>
        Regex.Matches(html, "<script[^>]*>").Select(match => match.Value).ToList();

    [Fact]
    public void Write_NonceSupplied_IsOnEveryInlineScript()
    {
        var html = HtmlDocumentWriter.Write(Context("r4nd0m"));
        var tags = ScriptTags(html);

        tags.Count.ShouldBeGreaterThan(2);
        tags.ShouldAllBe(tag => tag.Contains("nonce=\"r4nd0m\""));
    }

    [Fact]
    public void Write_NonceSupplied_CoversTheImportMapModelAndMount()
    {
        // Named individually, because each one blocking breaks the page in a different way.
        var html = HtmlDocumentWriter.Write(Context("abc123"));

        html.ShouldContain("<script type=\"importmap\" nonce=\"abc123\">");
        html.ShouldContain("nonce=\"abc123\">{}</script>");
        html.ShouldContain("<script type=\"module\" nonce=\"abc123\">");
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    public void Write_NoNonce_WritesNoAttribute(string? nonce)
    {
        var html = HtmlDocumentWriter.Write(Context(nonce));

        html.ShouldNotContain("nonce=");
        html.ShouldContain("<script type=\"module\">");
    }

    [Fact]
    public void Write_NonceContainsMarkup_IsEscaped()
    {
        // A nonce is generated by the application, but it reaches the page as an attribute value
        // and is treated like any other.
        var html = HtmlDocumentWriter.Write(Context("\"><script>alert(1)</script>"));

        html.ShouldNotContain("<script>alert(1)</script>");
    }
}
