using System.Text;

namespace JsxCore.Compilation.Assets;

/// <summary>
/// The JavaScript behind <c>dotnet:globals</c>: one named export per registered .NET global.
/// </summary>
/// <remarks>
/// Generated rather than shipped, because the names come from the application's own registrations
/// and an ES module's exports have to be known statically. Each export is a proxy that resolves
/// nothing until a member is read, so a client-rendered view can import a global harmlessly and
/// only fails if it actually uses one.
/// </remarks>
public static class GeneratedGlobalsModule
{
    public const string FileName = "globals.js";

    public static string For(IEnumerable<string> globalNames)
    {
        ArgumentNullException.ThrowIfNull(globalNames);

        var names = globalNames.OrderBy(name => name, StringComparer.Ordinal).ToList();

        var builder = new StringBuilder();
        builder.AppendLine("// Generated by JsxCore from the globals registered with options.Globals.");
        builder.AppendLine("// Each export reaches the current request's instance, so holding one is safe.");
        builder.AppendLine();

        // The catch-all, alongside the named exports: a global registered under a name that is not
        // a valid identifier is reachable only this way, and so is one registered after startup.
        builder.AppendLine("""export { dotnet } from "./dotnet.js";""");
        builder.AppendLine();

        if (names.Count == 0)
        {
            return builder.ToString();
        }

        builder.AppendLine("""import { dotnetGlobal } from "./dotnet.js";""");
        builder.AppendLine();

        foreach (var name in names.Where(IsUsableAsIdentifier))
        {
            builder.Append("export const ").Append(name).Append(" = dotnetGlobal(\"").Append(name).AppendLine("\");");
        }

        return builder.ToString();
    }

    /// <summary>
    /// A global can be registered under any string; only some of those are importable names.
    /// </summary>
    /// <remarks>
    /// One registered as "my service" is still reachable through the catch-all object, so nothing
    /// is lost by leaving it out of here, where it would be a syntax error.
    /// </remarks>
    private static bool IsUsableAsIdentifier(string name) =>
        name.Length > 0
        && (char.IsLetter(name[0]) || name[0] is '_' or '$')
        && name.All(character => char.IsLetterOrDigit(character) || character is '_' or '$');
}
