using System.Text;
using System.Text.RegularExpressions;
using JsxCore.Compilation;
using JsxCore.Compilation.Modules;
using JsxCore.Compilation.Provisioning;

namespace JsxCore.Tool;

public static partial class AnalyseCommand
{
    public static int Run(Arguments arguments)
    {
        var projectDirectory = arguments.Required("project-dir");
        var output = arguments.Required("output");
        var layout = NodeModulesLayout.For(projectDirectory, arguments.List("search-paths"));
        var manifest = PackageManifest.Nearest(projectDirectory);

        var props = new StringBuilder();
        props.AppendLine("<!-- Generated by JsxCore. Edits are overwritten on the next build. -->");
        props.AppendLine("<Project>");
        props.AppendLine("  <PropertyGroup>");
        Property(props, "JsxCoreNodeModulesRoot", layout.Roots.FirstOrDefault());
        Property(props, "JsxCoreManifestPath", manifest?.Path);
        Property(props, "JsxCoreManifestDirectory", manifest is null ? null : Path.GetDirectoryName(manifest.Path));
        Property(props, "JsxCoreResolvedCompilerPath", TypeScriptToolchainLocator.CandidatePaths(layout).FirstOrDefault(File.Exists));
        props.AppendLine("  </PropertyGroup>");

        props.AppendLine("  <ItemGroup>");
        foreach (var package in manifest?.Packages ?? [])
        {
            var installed = layout.FindFile($"{package.Name}/package.json");

            props.Append("    <")
                .Append(package.Development ? "JsxCoreNpmDevDependency" : "JsxCoreNpmDependency")
                .Append(" Include=\"").Append(Escape(package.Name)).Append('"')
                .Append(" Range=\"").Append(Escape(package.Range)).Append('"')
                // PackageLabel, not Label: Label is a reserved MSBuild attribute and would be read as the
                // element's label rather than as item metadata.
                .Append(" PackageLabel=\"").Append(Escape(Label(package))).Append('"')
                .Append(" InstalledManifest=\"").Append(Escape(installed ?? string.Empty)).Append('"')
                .Append(" Installed=\"").Append(installed is null ? "false" : "true").Append('"')
                .AppendLine(" Visible=\"false\" />");
        }
        props.AppendLine("  </ItemGroup>");
        props.AppendLine("</Project>");

        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(output))!);

        // Rewriting an identical file would retrigger evaluation in an editor watching it.
        var text = props.ToString();
        if (!File.Exists(output) || File.ReadAllText(output) != text)
        {
            File.WriteAllText(output, text);
        }

        return 0;
    }

    public static string Label(DeclaredPackage package) =>
        PlainVersion().IsMatch(package.Range) ? $"{package.Name}@{package.Range}" : package.Name;

    private static void Property(StringBuilder builder, string name, string? value)
    {
        if (!string.IsNullOrEmpty(value))
        {
            builder.Append("    <").Append(name).Append('>')
                .Append(Escape(value)).Append("</").Append(name).AppendLine(">");
        }
    }

    private static string Escape(string value) => value
        .Replace("&", "&amp;", StringComparison.Ordinal)
        .Replace("<", "&lt;", StringComparison.Ordinal)
        .Replace(">", "&gt;", StringComparison.Ordinal)
        .Replace("\"", "&quot;", StringComparison.Ordinal)
        .Replace(";", "%3B", StringComparison.Ordinal);

    [GeneratedRegex(@"^[\^~]?[0-9][0-9A-Za-z.\-+]*$")]
    private static partial Regex PlainVersion();
}
