using System.Text;
using System.Text.RegularExpressions;
using JsxCore.Compilation;
using JsxCore.Compilation.Modules;
using JsxCore.Compilation.Provisioning;

namespace JsxCore.Tool;

public static partial class AnalyseCommand
{
    public static int Run(Arguments arguments)
    {
        var projectDirectory = arguments.Required("project-dir");
        var output = arguments.Required("output");
        var layout = NodeModulesLayout.For(projectDirectory, arguments.List("search-paths"));
        var manifest = PackageManifest.Nearest(projectDirectory);

        var props = new StringBuilder();
        props.AppendLine("<!-- Generated by JsxCore. Edits are overwritten on the next build. -->");
        props.AppendLine("<Project>");
        props.AppendLine("  <PropertyGroup>");
        Property(props, "JsxCoreNodeModulesRoot", layout.Roots.FirstOrDefault());
        Property(props, "JsxCoreManifestPath", manifest?.Path);
        Property(props, "JsxCoreManifestDirectory", manifest is null ? null : Path.GetDirectoryName(manifest.Path));
        Property(props, "JsxCoreResolvedCompilerPath", TypeScriptToolchainLocator.CandidatePaths(layout).FirstOrDefault(File.Exists));
        props.AppendLine("  </PropertyGroup>");

        props.AppendLine("  <ItemGroup>");
        foreach (var package in manifest?.Packages ?? [])
        {
            var installed = layout.FindFile($"{package.Name}/package.json");

            props.Append("    <")
                .Append(package.Development ? "JsxCoreNpmDevDependency" : "JsxCoreNpmDependency")
                .Append(" Include=\"").Append(Escape(package.Name)).Append('"')
                .Append(" Range=\"").Append(Escape(package.Range)).Append('"')
                // PackageLabel, not Label: Label is a reserved MSBuild attribute and would be read as the
                // element's label rather than as item metadata.
                .Append(" PackageLabel=\"").Append(Escape(Label(package))).Append('"')
                .Append(" InstalledManifest=\"").Append(Escape(installed ?? string.Empty)).Append('"')
                .Append(" Installed=\"").Append(installed is null ? "false" : "true").Append('"')
                .AppendLine(" Visible=\"false\" />");
        }
        // Everything the runtime actually needs, which is the declared dependencies plus theirs,
        // and theirs. react-dom needs scheduler; publishing only what package.json names leaves an
        // application that resolves react-dom and then fails on the first render.
        props.AppendLine("  </ItemGroup>");
        props.AppendLine("  <ItemGroup>");
        foreach (var name in RuntimeClosure(manifest, layout))
        {
            props.Append("    <JsxCoreNpmRuntimePackage Include=\"").Append(Escape(name))
                 .AppendLine("\" Visible=\"false\" />");
        }
        props.AppendLine("  </ItemGroup>");
        props.AppendLine("</Project>");

        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(output))!);

        // Rewriting an identical file would retrigger evaluation in an editor watching it.
        var text = props.ToString();
        if (!File.Exists(output) || File.ReadAllText(output) != text)
        {
            File.WriteAllText(output, text);
        }

        return 0;
    }

    public static string Label(DeclaredPackage package) =>
        PlainVersion().IsMatch(package.Range) ? $"{package.Name}@{package.Range}" : package.Name;

    private static void Property(StringBuilder builder, string name, string? value)
    {
        if (!string.IsNullOrEmpty(value))
        {
            builder.Append("    <").Append(name).Append('>')
                .Append(Escape(value)).Append("</").Append(name).AppendLine(">");
        }
    }

    /// <summary>
    /// The runtime dependency closure: what has to be present for a view to render, walked through
    /// the installed packages rather than read off the manifest.
    /// </summary>
    /// <remarks>
    /// A package's own devDependencies are not included, which is the cut npm makes when installing
    /// it as a dependency. A package that is declared but not installed contributes only itself.
    /// </remarks>
    private static IReadOnlyList<string> RuntimeClosure(PackageManifest? manifest, NodeModulesLayout layout)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var queue = new Queue<string>(
            (manifest?.Packages ?? []).Where(package => !package.Development).Select(package => package.Name));

        while (queue.Count > 0)
        {
            var name = queue.Dequeue();
            if (!seen.Add(name))
            {
                continue;
            }

            if (layout.FindFile($"{name}/package.json") is not { } path
                || PackageManifest.Read(path) is not { } installed)
            {
                continue;
            }

            foreach (var dependency in installed.Packages.Where(package => !package.Development))
            {
                queue.Enqueue(dependency.Name);
            }
        }

        return [.. seen.OrderBy(name => name, StringComparer.Ordinal)];
    }

    private static string Escape(string value) => value
        .Replace("&", "&amp;", StringComparison.Ordinal)
        .Replace("<", "&lt;", StringComparison.Ordinal)
        .Replace(">", "&gt;", StringComparison.Ordinal)
        .Replace("\"", "&quot;", StringComparison.Ordinal)
        .Replace(";", "%3B", StringComparison.Ordinal);

    [GeneratedRegex(@"^[\^~]?[0-9][0-9A-Za-z.\-+]*$")]
    private static partial Regex PlainVersion();
}
